#!/usr/bin/env python3

"""
Created on 5 Dec 2016

@author: Bruno Beloff (bruno.beloff@southcoastscience.com)

DESCRIPTION
The status_sampler utility is used to report on the configuration and condition of the host system and its
peripherals. Items included in the report vary depending on the hardware configuration of the equipment. Fields
which are always reported include:

* Sensing schedule
* Timezone
* Unix uptime report

Fields which may be reported include:

* AirNowSiteConf
* GPS location
* PSU status
* Temperature of the host processor
* Temperature of the digital front-end board

The status_sampler attempts to obtain a PSU status report from a file generated by psu_monitor utility.

The status_sampler writes its output to stdout, unless suppressed. As for all sensing utilities, the output format is a
JSON document with fields for:

* the unique tag of the device (if the system ID is set)
* the recording date / time in ISO 8601 format
* a value field containing the sensed values

Command-line options allow for single-shot reading, multiple readings with specified time intervals, or readings
controlled by an independent scheduling process via a Unix semaphore.

SYNOPSIS
status_sampler.py [{ -s SEMAPHORE | -i INTERVAL [-n SAMPLES] }] [-v]

EXAMPLES
./status_sampler.py -i 60

FILES
~/SCS/conf/schedule.json
~/SCS/conf/system_id.json

DOCUMENT EXAMPLE - OUTPUT
{"rec": "2021-10-06T11:13:07Z", "tag": "scs-be2-3", "ver": 1.0, "val": {"tz": {"name": "Europe/London",
"utc-offset": "+01:00"}, "gps": {"pos": [null, null], "elv": null, "qual": 0},
"sch": {"scs-climate": {"interval": 60.0, "tally": 1}, "scs-gases": {"interval": 10.0, "tally": 1},
"scs-status": {"interval": 60.0, "tally": 1}}, "tmp": {"brd": 29.4}, "up": {"period": "00-00:22:00", "users": 3,
"load": {"av1": 0.02, "av5": 0.34, "av15": 0.67}}, "sig": {"quality": null, "recent": null}}}

SEE ALSO
scs_dev/interface_power
scs_dev/psu_monitor
scs_dev/scheduler

scs_mfr/airnow_conf
scs_mfr/gps_conf
scs_mfr/modem
scs_mfr/schedule
scs_mfr/system_id
scs_mfr/timezone

RESOURCES
https://en.wikipedia.org/wiki/ISO_8601

BUGS
If status_sampler is run in single-shot mode, the GPS monitor may time out before being able to supply data.
"""

import sys
import time

from scs_core.aqcsv.conf.airnow_site_conf import AirNowSiteConf

from scs_core.data.json import JSONify

from scs_core.sync.schedule import Schedule
from scs_core.sync.timed_runner import TimedRunner

from scs_core.sys.logging import Logging
from scs_core.sys.signalled_exit import SignalledExit
from scs_core.sys.system_id import SystemID

from scs_dev.cmd.cmd_status_sampler import CmdStatusSampler
from scs_dev.sampler.status_sampler import StatusSampler

from scs_dfe.gps.gps_conf import GPSConf
from scs_dfe.interface.interface_conf import InterfaceConf

from scs_host.bus.i2c import I2C
from scs_host.sync.schedule_runner import ScheduleRunner
from scs_host.sys.host import Host

try:
    from scs_psu.psu.psu_conf import PSUConf
except ImportError:
    from scs_core.psu.psu_conf import PSUConf


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    sampler = None

    # ----------------------------------------------------------------------------------------------------------------
    # cmd...

    cmd = CmdStatusSampler()

    # logging...
    Logging.config('status_sampler', verbose=cmd.verbose)
    logger = Logging.getLogger()

    logger.info(cmd)

    try:
        I2C.Sensors.open()
        I2C.Utilities.open()

        # ------------------------------------------------------------------------------------------------------------
        # resources...

        # Schedule...
        schedule = Schedule.load(Host)

        # SystemID...
        system_id = SystemID.load(Host)

        tag = None if system_id is None else system_id.message_tag()

        if system_id:
            logger.info(system_id)

        # AirNow...
        airnow = AirNowSiteConf.load(Host)

        if airnow:
            logger.info(airnow)

        # Interface...
        interface_conf = InterfaceConf.load(Host)
        interface = None if interface_conf is None else interface_conf.interface()
        interface_model = None if interface_conf is None else interface_conf.model

        # GPS...
        gps_conf = GPSConf.load(Host)
        gps_monitor = None if gps_conf is None else gps_conf.gps_monitor(interface, Host)

        # PSUConf...
        psu_conf = PSUConf.load(Host)

        # sampler...
        runner = TimedRunner(cmd.interval, cmd.samples) if cmd.semaphore is None \
            else ScheduleRunner(cmd.semaphore)

        sampler = StatusSampler(runner, tag, airnow, interface, gps_monitor, psu_conf)

        logger.info(sampler)


        # ------------------------------------------------------------------------------------------------------------
        # check...

        if cmd.semaphore and (schedule is None or not schedule.contains(cmd.semaphore)):
            logger.info("no schedule - halted.")

            while True:
                time.sleep(60.0)


        # ------------------------------------------------------------------------------------------------------------
        # run...

        # signal handler...
        SignalledExit.construct("status_sampler", cmd.verbose)

        sampler.start()

        for sample in sampler.samples():
            logger.info("      rec: %s" % sample.rec.as_time())

            print(JSONify.dumps(sample.as_json()))
            sys.stdout.flush()


    # ----------------------------------------------------------------------------------------------------------------
    # end...

    except ConnectionError as ex:
        logger.error(ex)

    except (KeyboardInterrupt, SystemExit):
        pass

    finally:
        if cmd:
            logger.info("finishing")

        if sampler:
            sampler.stop()

        I2C.Sensors.close()
        I2C.Utilities.close()
